import { Ionicons } from "@expo/vector-icons";
import { EventItem } from "../interfaces/interfaces";

export const calendarEvents = [
    {
      id: 1,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
    {
      id: 2,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
    {
      id: 3,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
]

export const homeStatsData: { title: string; value: string; icon: React.ComponentProps<typeof Ionicons>['name']; desc: string }[] = [ 
  { 
    title: 'News', 
    value: '134,348', 
    icon: 'reader', 
    desc: 'Get instant updates and announcements from your institute.' 
  },
  { 
    title: 'Events', 
    value: '145', 
    icon: 'calendar', 
    desc: 'Stay on top of upcoming academic and social events.' 
  },
  { 
    title: 'Projects', 
    value: '1034', 
    icon: 'folder', 
    desc: 'Discover creative projects shared by students and staff.' 
  },
  { 
    title: 'Users', 
    value: '5000+', 
    icon: 'people', 
    desc: 'Join a vibrant community of learners and educators.' 
  },
];

export const events: EventItem[] = [
  // October 2025
  {
    _id: 1,
    title: 'DDS Youth Engineering Event',
    location: 'Teaching Tower Basement (TT-B)',
    category: 'Engineering Event',
    date: '24/10/2025',
    start: '09:00 AM',
    end: '11:00 AM',
    isFavorite: true,
  },
  {
    _id: 2,
    title: 'Career Fair Prep Session',
    location: 'Campus Plaza',
    category: 'Preparation',
    date: '25/10/2025',
    start: '02:00 PM',
    end: '04:00 PM',
    isFavorite: false,
  },
  {
    _id: 100,
    title: 'Robotics Competition Prep',
    location: 'Engineering Lab',
    category: 'Preparation',
    date: '28/10/2026',
    start: '09:00 AM',
    end: '11:00 AM',
    isFavorite: true,
  },
  // November 2025
  {
    _id: 3,
    title: 'AI Seminar for Beginners',
    location: 'Lecture Hall A',
    category: 'Seminar',
    date: '05/11/2025',
    start: '10:00 AM',
    end: '12:00 PM',
    isFavorite: true,
  },
  {
    _id: 4,
    title: 'Campus Sustainability Workshop',
    location: 'Green Auditorium',
    category: 'Workshop',
    date: '18/11/2025',
    start: '03:00 PM',
    end: '05:00 PM',
    isFavorite: false,
  },
  // December 2025
  {
    _id: 5,
    title: 'Math Olympiad Practice',
    location: 'Math Lab 101',
    category: 'Practice Session',
    date: '03/12/2025',
    start: '09:00 AM',
    end: '11:00 AM',
    isFavorite: true,
  },
  {
    _id: 6,
    title: 'Literature Club Meeting',
    location: 'Library Conference Room',
    category: 'Club Meeting',
    date: '15/12/2025',
    start: '02:00 PM',
    end: '04:00 PM',
    isFavorite: false,
  },
  // January 2026
  {
    _id: 7,
    title: 'Robotics Competition Prep',
    location: 'Engineering Lab',
    category: 'Preparation',
    date: '10/01/2026',
    start: '09:00 AM',
    end: '11:00 AM',
    isFavorite: true,
  },
  {
    _id: 8,
    title: 'Guest Lecture on Quantum Computing',
    location: 'Main Hall',
    category: 'Lecture',
    date: '25/01/2026',
    start: '01:00 PM',
    end: '03:00 PM',
    isFavorite: false,
  },
  // February 2026
  {
    _id: 9,
    title: 'Art Exhibition Opening',
    location: 'Art Gallery',
    category: 'Exhibition',
    date: '05/02/2026',
    start: '05:00 PM',
    end: '07:00 PM',
    isFavorite: true,
  },
  {
    _id: 10,
    title: 'Sports Day Trials',
    location: 'Sports Ground',
    category: 'Trials',
    date: '20/02/2026',
    start: '08:00 AM',
    end: '12:00 PM',
    isFavorite: false,
  },
  // March 2026
  {
    _id: 11,
    title: 'Coding Bootcamp',
    location: 'Computer Lab 202',
    category: 'Bootcamp',
    date: '10/03/2026',
    start: '09:00 AM',
    end: '05:00 PM',
    isFavorite: true,
  },
  {
    _id: 12,
    title: 'Music Concert Rehearsal',
    location: 'Music Room',
    category: 'Rehearsal',
    date: '25/03/2026',
    start: '02:00 PM',
    end: '04:00 PM',
    isFavorite: false,
  },
  // April 2026
  {
    _id: 13,
    title: 'Environmental Science Field Trip',
    location: 'Off-Campus',
    category: 'Field Trip',
    date: '05/04/2026',
    start: '08:00 AM',
    end: '04:00 PM',
    isFavorite: true,
  },
  {
    _id: 14,
    title: 'Hackathon Kickoff',
    location: 'Innovation Center',
    category: 'Hackathon',
    date: '20/04/2026',
    start: '06:00 PM',
    end: '08:00 PM',
    isFavorite: false,
  },
  // May 2026
  {
    _id: 15,
    title: 'Career Fair',
    location: 'Campus Plaza',
    category: 'Fair',
    date: '10/05/2026',
    start: '10:00 AM',
    end: '04:00 PM',
    isFavorite: true,
  },
  {
    _id: 16,
    title: 'Alumni Networking Event',
    location: 'Alumni Hall',
    category: 'Networking',
    date: '25/05/2026',
    start: '07:00 PM',
    end: '09:00 PM',
    isFavorite: false,
  },
  // June 2026
  {
    _id: 17,
    title: 'Science Fair Prep',
    location: 'Science Lab',
    category: 'Preparation',
    date: '05/06/2026',
    start: '09:00 AM',
    end: '01:00 PM',
    isFavorite: true,
  },
  {
    _id: 18,
    title: 'Drama Club Rehearsal',
    location: 'Theater Room',
    category: 'Rehearsal',
    date: '20/06/2026',
    start: '03:00 PM',
    end: '05:00 PM',
    isFavorite: false,
  },
  // July 2026
  {
    _id: 19,
    title: 'Tech Innovation Workshop',
    location: 'Innovation Hub',
    category: 'Workshop',
    date: '10/07/2026',
    start: '10:00 AM',
    end: '02:00 PM',
    isFavorite: true,
  },
  {
    _id: 20,
    title: 'History Lecture Series',
    location: 'Lecture Hall B',
    category: 'Lecture',
    date: '25/07/2026',
    start: '01:00 PM',
    end: '03:00 PM',
    isFavorite: false,
  },
  // August 2026
  {
    _id: 21,
    title: 'Photography Contest',
    location: 'Art Gallery',
    category: 'Contest',
    date: '05/08/2026',
    start: '09:00 AM',
    end: '12:00 PM',
    isFavorite: true,
  },
  {
    _id: 22,
    title: 'Health Awareness Seminar',
    location: 'Health Center',
    category: 'Seminar',
    date: '20/08/2026',
    start: '02:00 PM',
    end: '04:00 PM',
    isFavorite: false,
  },
  // September 2026
  {
    _id: 23,
    title: 'Debate Club Finals',
    location: 'Auditorium',
    category: 'Competition',
    date: '10/09/2026',
    start: '06:00 PM',
    end: '08:00 PM',
    isFavorite: true,
  },
  {
    _id: 24,
    title: 'Gardening Workshop',
    location: 'Botanical Garden',
    category: 'Workshop',
    date: '25/09/2026',
    start: '10:00 AM',
    end: '01:00 PM',
    isFavorite: false,
  },
  // October 2026
  
];