import { Ionicons } from "@expo/vector-icons";
import { EventItem, NewsItem, ProjectsItem } from "../interfaces/interfaces";

export const calendarEvents = [
    {
      id: 1,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
    {
      id: 2,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
    {
      id: 3,
      date: '12/11/2025',
      title: 'DDS Youth engineering event',
      location: 'Teaching Tower Basement (TT-B)',
      category: 'Engineering event',
    },
]

export const homeStatsData: { title: string; value: string; icon: React.ComponentProps<typeof Ionicons>['name']; desc: string }[] = [ 
  { 
    title: 'News', 
    value: '134,348', 
    icon: 'reader', 
    desc: 'Get instant updates and announcements from your institute.' 
  },
  { 
    title: 'Events', 
    value: '145', 
    icon: 'calendar', 
    desc: 'Stay on top of upcoming academic and social events.' 
  },
  { 
    title: 'Projects', 
    value: '1034', 
    icon: 'folder', 
    desc: 'Discover creative projects shared by students and staff.' 
  },
  { 
    title: 'Users', 
    value: '5000+', 
    icon: 'people', 
    desc: 'Join a vibrant community of learners and educators.' 
  },
];

export const events: EventItem[] = [
  {
    _id: "1",
    userId: "demo-user",
    header: "DDS Youth Engineering Event",
    location: "Teaching Tower Basement (TT-B)",
    category: "Engineering Event",
    date: "24/10/2025",
    start: "09:00 AM",
    end: "11:00 AM",
    favorites: ["demo-user"],
    img: "",
    desc: "DDS Youth Engineering Event",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "2",
    userId: "demo-user",
    header: "Career Fair Prep Session",
    location: "Campus Plaza",
    category: "Preparation",
    date: "25/10/2025",
    start: "02:00 PM",
    end: "04:00 PM",
    favorites: [],
    img: "",
    desc: "Career Fair Prep Session",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "100",
    userId: "demo-user",
    header: "Robotics Competition Prep",
    location: "Engineering Lab",
    category: "Preparation",
    date: "28/10/2026",
    start: "09:00 AM",
    end: "11:00 AM",
    favorites: ["demo-user"],
    img: "",
    desc: "Robotics Competition Prep",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // November 2025
  {
    _id: "3",
    userId: "demo-user",
    header: "AI Seminar for Beginners",
    location: "Lecture Hall A",
    category: "Seminar",
    date: "05/11/2025",
    start: "10:00 AM",
    end: "12:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "AI Seminar for Beginners",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "4",
    userId: "demo-user",
    header: "Campus Sustainability Workshop",
    location: "Green Auditorium",
    category: "Workshop",
    date: "18/11/2025",
    start: "03:00 PM",
    end: "05:00 PM",
    favorites: [],
    img: "",
    desc: "Campus Sustainability Workshop",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // December 2025
  {
    _id: "5",
    userId: "demo-user",
    header: "Math Olympiad Practice",
    location: "Math Lab 101",
    category: "Practice Session",
    date: "03/12/2025",
    start: "09:00 AM",
    end: "11:00 AM",
    favorites: ["demo-user"],
    img: "",
    desc: "Math Olympiad Practice",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "6",
    userId: "demo-user",
    header: "Literature Club Meeting",
    location: "Library Conference Room",
    category: "Club Meeting",
    date: "15/12/2025",
    start: "02:00 PM",
    end: "04:00 PM",
    favorites: [],
    img: "",
    desc: "Literature Club Meeting",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // January 2026
  {
    _id: "7",
    userId: "demo-user",
    header: "Robotics Competition Prep",
    location: "Engineering Lab",
    category: "Preparation",
    date: "10/01/2026",
    start: "09:00 AM",
    end: "11:00 AM",
    favorites: ["demo-user"],
    img: "",
    desc: "Robotics Competition Prep",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "8",
    userId: "demo-user",
    header: "Guest Lecture on Quantum Computing",
    location: "Main Hall",
    category: "Lecture",
    date: "25/01/2026",
    start: "01:00 PM",
    end: "03:00 PM",
    favorites: [],
    img: "",
    desc: "Guest Lecture on Quantum Computing",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // February 2026
  {
    _id: "9",
    userId: "demo-user",
    header: "Art Exhibition Opening",
    location: "Art Gallery",
    category: "Exhibition",
    date: "05/02/2026",
    start: "05:00 PM",
    end: "07:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Art Exhibition Opening",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "10",
    userId: "demo-user",
    header: "Sports Day Trials",
    location: "Sports Ground",
    category: "Trials",
    date: "20/02/2026",
    start: "08:00 AM",
    end: "12:00 PM",
    favorites: [],
    img: "",
    desc: "Sports Day Trials",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // March 2026
  {
    _id: "11",
    userId: "demo-user",
    header: "Coding Bootcamp",
    location: "Computer Lab 202",
    category: "Bootcamp",
    date: "10/03/2026",
    start: "09:00 AM",
    end: "05:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Coding Bootcamp",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "12",
    userId: "demo-user",
    header: "Music Concert Rehearsal",
    location: "Music Room",
    category: "Rehearsal",
    date: "25/03/2026",
    start: "02:00 PM",
    end: "04:00 PM",
    favorites: [],
    img: "",
    desc: "Music Concert Rehearsal",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // April 2026
  {
    _id: "13",
    userId: "demo-user",
    header: "Environmental Science Field Trip",
    location: "Off-Campus",
    category: "Field Trip",
    date: "05/04/2026",
    start: "08:00 AM",
    end: "04:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Environmental Science Field Trip",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "14",
    userId: "demo-user",
    header: "Hackathon Kickoff",
    location: "Innovation Center",
    category: "Hackathon",
    date: "20/04/2026",
    start: "06:00 PM",
    end: "08:00 PM",
    favorites: [],
    img: "",
    desc: "Hackathon Kickoff",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // May 2026
  {
    _id: "15",
    userId: "demo-user",
    header: "Career Fair",
    location: "Campus Plaza",
    category: "Fair",
    date: "10/05/2026",
    start: "10:00 AM",
    end: "04:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Career Fair",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "16",
    userId: "demo-user",
    header: "Alumni Networking Event",
    location: "Alumni Hall",
    category: "Networking",
    date: "25/05/2026",
    start: "07:00 PM",
    end: "09:00 PM",
    favorites: [],
    img: "",
    desc: "Alumni Networking Event",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // June 2026
  {
    _id: "17",
    userId: "demo-user",
    header: "Science Fair Prep",
    location: "Science Lab",
    category: "Preparation",
    date: "05/06/2026",
    start: "09:00 AM",
    end: "01:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Science Fair Prep",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "18",
    userId: "demo-user",
    header: "Drama Club Rehearsal",
    location: "Theater Room",
    category: "Rehearsal",
    date: "20/06/2026",
    start: "03:00 PM",
    end: "05:00 PM",
    favorites: [],
    img: "",
    desc: "Drama Club Rehearsal",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // July 2026
  {
    _id: "19",
    userId: "demo-user",
    header: "Tech Innovation Workshop",
    location: "Innovation Hub",
    category: "Workshop",
    date: "10/07/2026",
    start: "10:00 AM",
    end: "02:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Tech Innovation Workshop",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "20",
    userId: "demo-user",
    header: "History Lecture Series",
    location: "Lecture Hall B",
    category: "Lecture",
    date: "25/07/2026",
    start: "01:00 PM",
    end: "03:00 PM",
    favorites: [],
    img: "",
    desc: "History Lecture Series",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // August 2026
  {
    _id: "21",
    userId: "demo-user",
    header: "Photography Contest",
    location: "Art Gallery",
    category: "Contest",
    date: "05/08/2026",
    start: "09:00 AM",
    end: "12:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Photography Contest",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "22",
    userId: "demo-user",
    header: "Health Awareness Seminar",
    location: "Health Center",
    category: "Seminar",
    date: "20/08/2026",
    start: "02:00 PM",
    end: "04:00 PM",
    favorites: [],
    img: "",
    desc: "Health Awareness Seminar",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },

  // September 2026
  {
    _id: "23",
    userId: "demo-user",
    header: "Debate Club Finals",
    location: "Auditorium",
    category: "Competition",
    date: "10/09/2026",
    start: "06:00 PM",
    end: "08:00 PM",
    favorites: ["demo-user"],
    img: "",
    desc: "Debate Club Finals",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  },
  {
    _id: "24",
    userId: "demo-user",
    header: "Gardening Workshop",
    location: "Botanical Garden",
    category: "Workshop",
    date: "25/09/2026",
    start: "10:00 AM",
    end: "01:00 PM",
    favorites: [],
    img: "",
    desc: "Gardening Workshop",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z"
  }
];

export const news = [
  {
    _id: 1,
    header: 'New Engineering Lab Opens',
    img: 'https://firebasestorage.googleapis.com/v0/b/instiwise-testing.appspot.com/o/1693379970989_a7f66b3b-fb7c-4d76-a464-056e23d3d289.jpeg?alt=media&token=7860084b-a925-43af-b70c-015c47355fbb',
    desc: 'The new engineering lab was inaugurated today, offering state-of-the-art facilities for students.',
    likes: [1, 2, 3],
    dislikes: [4],
    views: [1, 2, 3, 4, 5],
    createdAt: '2025-10-18T09:00:00Z',
  },
  {
    _id: 2,
    header: 'AI Course Enrollment Begins',
    desc: 'Sign up for the upcoming AI course starting next month.',
    likes: [5, 6],
    dislikes: [],
    views: [1, 2, 5, 6, 7],
    createdAt: '2025-10-17T15:30:00Z',
  },
  {
    _id: 3,
    header: 'Campus Sustainability Initiative',
    img: 'https://deohs.washington.edu/sites/default/files/styles/hero_full_narrow/public/blog/MicrosoftTeams-image%20%2814%29-hero.jpg?itok=qEhwpOGg',
    desc: 'Join our new initiative to make the campus more sustainable.',
    likes: [7, 8],
    dislikes: [9],
    views: [1, 7, 8, 9, 10],
    createdAt: '2025-10-15T11:00:00Z',
  },
  {
    _id: 4,
    header: 'Math Olympiad Winners Announced',
    desc: 'Congratulations to the students who excelled in the Math Olympiad!',
    likes: [10, 11],
    dislikes: [],
    views: [1, 10, 11, 12],
    createdAt: '2025-10-10T14:00:00Z',
  },
  {
    _id: 5,
    header: 'Literature Club Event',
    img: 'https://schoolreadinglist.co.uk/wp-content/uploads/2012/05/literaryeventsandfestivals.jpg',
    desc: 'Join us for a poetry reading session this Friday.',
    likes: [12, 13],
    dislikes: [14],
    views: [1, 12, 13, 14, 15],
    createdAt: '2025-09-28T18:00:00Z',
  },
  {
    _id: 6,
    header: 'Art Exhibition Preview',
    desc: 'Preview the upcoming art exhibition featuring student works.',
    likes: [17, 18],
    dislikes: [19],
    views: [1, 17, 18, 19, 20],
    createdAt: '2025-09-15T13:00:00Z',
  },
  {
    _id: 7,
    header: 'Robotics Competition Update',
    img: 'https://humanainternational.com/wp-content/uploads/2024/08/robotic.png',
    desc: 'Get the latest updates on the upcoming robotics competition.',
    likes: [15, 16],
    dislikes: [],
    views: [1, 15, 16, 17],
    createdAt: '2025-09-20T10:00:00Z',
  },
  {
    _id: 9,
    header: 'Coding Bootcamp Registration',
    desc: 'Register now for the intensive coding bootcamp in March.',
    likes: [22, 23],
    dislikes: [24],
    views: [1, 22, 23, 24, 25],
    createdAt: '2025-08-25T17:00:00Z',
  },
  {
    _id: 8,
    header: 'Sports Day Schedule Released',
    img: 'https://www.mayoornoida.net//public/admin/assets/images/blog/banner/desktop/1746619106-WhatsApp%20Image%202025-05-07%20at%2016.47.14.jpeg',
    desc: 'Check out the schedule for the annual sports day event.',
    likes: [20, 21],
    dislikes: [],
    views: [1, 20, 21, 22],
    createdAt: '2025-09-01T08:00:00Z',
  },
  {
    _id: 10,
    header: 'Alumni Networking Event',
    desc: 'Connect with alumni at our networking event next month.',
    likes: [25, 26],
    dislikes: [],
    views: [1, 25, 26, 27],
    createdAt: '2025-08-10T12:00:00Z',
  },
];

export const projects = [
  {
    _id: 1,
    title: 'Virtual Reality Lab',
    userId: 'user005',
    description: 'Setting up a VR lab for immersive learning experiences.',
    img: 'https://cdn.mos.cms.futurecdn.net/MWLF9tpHEo6iNHNj4BW3TS-1200-80.jpg',
    category: 'Technology',
    problem: 'Limited hands-on learning tools.',
    owner: 'Mike Brown',
    duration: '7 months',
    status: 'in progress',
    goals: ['Enhance VR education', 'Cross-department use'],
    resources: ['VR headsets', 'Software licenses'],
    budget: [10000, 4000],
    scope: ['History simulations', 'Engineering designs'],
    plan: ['Equipment setup', 'Training'],
    challenges: ['Cost', 'Technical support'],
    likes: [11, 12, 13],
    createdAt: '2025-10-13T15:00:00Z',
    updatedAt: '2025-10-13T15:00:00Z',
  },
  {
    _id: 2,
    title: 'Coding Hackathon',
    userId: 'user010',
    description: 'Organizing a hackathon to foster coding skills.',
    img: 'https://miro.medium.com/v2/resize:fit:1200/0*XDkvtDSZ22rR5Zvy.png',
    category: 'Technology',
    problem: 'Lack of coding competitions.',
    owner: 'Chris Taylor',
    duration: '2 months',
    status: 'on hold',
    goals: ['Skill enhancement', 'Innovation'],
    resources: ['Laptops', 'Internet'],
    budget: [3500, 800],
    scope: ['Team projects', 'Prizes'],
    plan: ['Registration', 'Event'],
    challenges: ['Participant turnout', 'Time'],
    likes: [24, 25],
    createdAt: '2025-10-18T10:00:00Z',
    updatedAt: '2025-10-18T10:00:00Z',
  },
  {
    _id: 3,
    title: 'AI Tutoring App',
    userId: 'user003',
    description: 'Building an AI-powered tutoring application for students.',
    img: 'https://play-lh.googleusercontent.com/pJ1iM2oJiUa-zII9EVYfLV_y5SIS_Y03YN9TCAkW_73P8kx1XIeF-1u5sUnze-F7k9k=w526-h296-rw',
    category: 'Education',
    problem: 'Limited access to personalized tutoring.',
    owner: 'Alex Johnson',
    duration: '6 months',
    status: 'in progress',
    goals: ['Enhance learning outcomes', 'Scalable solution'],
    resources: ['AI models', 'Mobile dev kit'],
    budget: [8000, 3000],
    scope: ['Math and science focus'],
    plan: ['Prototype', 'User testing'],
    challenges: ['AI accuracy', 'User adoption'],
    likes: [6, 7, 8],
    createdAt: '2025-10-11T14:00:00Z',
    updatedAt: '2025-10-11T14:00:00Z',
  },
  {
    _id: 4,
    title: 'Campus Safety App',
    userId: 'user004',
    description: 'Developing an app for campus safety alerts and tracking.',
    img: 'https://cdn-gnapb.nitrocdn.com/rVKsFrUUJpBqwSXDQLTtMASMDgzFisXl/assets/images/optimized/rev-774b768/www.octalsoftware.com/wp-content/uploads/2023/11/ezgif.com-webp-to-jpg-52-1024x683.jpg',
    category: 'Security',
    problem: 'Inadequate safety communication.',
    owner: 'Sarah Lee',
    duration: '5 months',
    status: 'completed',
    goals: ['Real-time alerts', 'Emergency tracking'],
    resources: ['GPS tech', 'Mobile framework'],
    budget: [6000, 1500],
    scope: ['Student safety', 'Staff integration'],
    plan: ['Development', 'Deployment'],
    challenges: ['Privacy concerns', 'Battery drain'],
    likes: [9, 10],
    createdAt: '2025-10-12T10:00:00Z',
    updatedAt: '2025-10-12T10:00:00Z',
  },
  {
    _id: 5,
    title: 'Smart Campus IoT System',
    userId: 'user001',
    description: 'Developing an IoT-based system to monitor campus utilities.',
    img: 'https://www.scnsoft.com/blog-pictures/internet-of-things/cover_.png',
    category: 'Technology',
    problem: 'Inefficient resource management on campus.',
    owner: 'John Doe',
    duration: '3 months',
    status: 'in progress',
    goals: ['Improve energy efficiency', 'Real-time monitoring'],
    resources: ['Sensors', 'Raspberry Pi', 'Cloud storage'],
    budget: [5000, 2000, 1000],
    scope: ['Indoor sensors', 'Outdoor monitoring'],
    plan: ['Phase 1: Setup', 'Phase 2: Testing'],
    challenges: ['Connectivity issues', 'Budget constraints'],
    likes: [1, 2, 3],
    createdAt: '2025-10-09T13:35:00Z',
    updatedAt: '2025-10-09T13:35:00Z',
  },
  {
    _id: 6,
    title: 'Community Cookbook',
    userId: 'user006',
    description: 'Compiling a digital cookbook with student recipes.',
    img: 'https://www.suntecdigital.com/blog/wp-content/uploads/2021/11/Create-Your-Own-Digital-Cookbook-1.jpg',
    category: 'Cultural',
    problem: 'Lack of cultural exchange platform.',
    owner: 'Emily Davis',
    duration: '3 months',
    status: 'on hold',
    goals: ['Cultural sharing', 'Digital archive'],
    resources: ['Recipe submissions', 'Design software'],
    budget: [2000, 500],
    scope: ['Student contributions', 'Online access'],
    plan: ['Collection', 'Publication'],
    challenges: ['Participation', 'Design'],
    likes: [14, 15],
    createdAt: '2025-10-14T11:00:00Z',
    updatedAt: '2025-10-14T11:00:00Z',
  },
  {
    _id: 7,
    title: 'Robotics Challenge',
    userId: 'user007',
    description: 'Organizing a robotics challenge for engineering students.',
    img: 'https://analyticsindiamag.com/wp-content/uploads/2019/05/first-nevada-robotics-robots_MEDIUM.jpg',
    category: 'Engineering',
    problem: 'Limited practical robotics experience.',
    owner: 'Tom Wilson',
    duration: '4 months',
    status: 'in progress',
    goals: ['Skill development', 'Competition'],
    resources: ['Robots', 'Venue'],
    budget: [5000, 1000],
    scope: ['Beginner level', 'Advanced category'],
    plan: ['Planning', 'Event day'],
    challenges: ['Equipment availability', 'Scheduling'],
    likes: [16, 17, 18],
    createdAt: '2025-10-15T13:00:00Z',
    updatedAt: '2025-10-15T13:00:00Z',
  },
  {
    _id: 8,
    title: 'Art Gallery Digitization',
    userId: 'user008',
    description: 'Digitizing the campus art gallery for online access.',
    img: 'https://www.artgalleryofhamilton.com/wp-content/uploads/2022/12/mike-shoot-feb-2020-1-768x768.jpg',
    category: 'Arts',
    problem: 'Limited physical access to artworks.',
    owner: 'Lisa Anderson',
    duration: '5 months',
    status: 'completed',
    goals: ['Online archive', 'Public access'],
    resources: ['Cameras', 'Web platform'],
    budget: [4000, 1200],
    scope: ['All exhibits', 'Metadata'],
    plan: ['Photography', 'Upload'],
    challenges: ['Image quality', 'Storage'],
    likes: [19, 20],
    createdAt: '2025-10-16T09:00:00Z',
    updatedAt: '2025-10-16T09:00:00Z',
  },
  {
    _id: 9,
    title: 'Health Awareness Campaign',
    userId: 'user009',
    description: 'Launching a campaign to promote student health awareness.',
    img: 'https://daniels.co.uk/wp-content/uploads/Health-Awareness-Events-2019-Feature.jpg',
    category: 'Health',
    problem: 'Low health awareness among students.',
    owner: 'Rachel Green',
    duration: '3 months',
    status: 'in progress',
    goals: ['Education', 'Workshops'],
    resources: ['Flyers', 'Speakers'],
    budget: [2500, 700],
    scope: ['Mental health', 'Physical fitness'],
    plan: ['Planning', 'Execution'],
    challenges: ['Engagement', 'Funding'],
    likes: [21, 22, 23],
    createdAt: '2025-10-17T14:00:00Z',
    updatedAt: '2025-10-17T14:00:00Z',
  },
  {
    _id: 10,
    title: 'Sustainable Garden Project',
    userId: 'user002',
    description: 'Creating a sustainable garden using recycled materials.',
    img: 'https://www.coolturf.com.au/wp-content/uploads/2020/10/coolturf-5-768x402.png',
    category: 'Environmental',
    problem: 'Lack of green spaces on campus.',
    owner: 'Jane Smith',
    duration: '4 months',
    status: 'on hold',
    goals: ['Increase biodiversity', 'Educational outreach'],
    resources: ['Recycled plastics', 'Soil', 'Plants'],
    budget: [3000, 500, 700],
    scope: ['Small garden plot', 'Community involvement'],
    plan: ['Design phase', 'Implementation'],
    challenges: ['Weather dependency', 'Funding'],
    likes: [4, 5],
    createdAt: '2025-10-10T09:00:00Z',
    updatedAt: '2025-10-10T09:00:00Z',
  },
];
